"""empty message

Revision ID: 0bb7289e78e2
Revises: 5b3f9208d5d4
Create Date: 2024-03-12 14:25:22.794019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0bb7289e78e2'
down_revision = '5b3f9208d5d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recording')
    op.add_column('analysis', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('class', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('class_assignment', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('notification', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('project', sa.Column('created_at_project', sa.DateTime(), nullable=False))
    op.add_column('task', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('task_project', sa.Column('created_at_task_project', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_column('task_project', 'created_at_task_project')
    op.drop_column('task', 'created_at')
    op.drop_column('project', 'created_at_project')
    op.drop_column('notification', 'created_at')
    op.drop_column('class_assignment', 'created_at')
    op.drop_column('class', 'created_at')
    op.drop_column('analysis', 'created_at')
    op.create_table('recording',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recording', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('analysis_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], name='recording_analysis_id_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='recording_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='recording_pkey')
    )
    # ### end Alembic commands ###
