"""empty message

Revision ID: 5b3f9208d5d4
Revises: 7240bb8f8792
Create Date: 2024-03-11 11:51:57.336721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3f9208d5d4'
down_revision = '7240bb8f8792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('task_project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notification', 'task_project', ['task_project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'task_project_id')
    # ### end Alembic commands ###
