"""empty message

Revision ID: 7240bb8f8792
Revises: 5c2702d23d12
Create Date: 2024-03-11 11:50:33.010726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7240bb8f8792'
down_revision = '5c2702d23d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_project', sa.Column('task_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task_project', 'task', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_project', type_='foreignkey')
    op.drop_column('task_project', 'task_id')
    # ### end Alembic commands ###
