"""empty message

Revision ID: b813c5983b99
Revises: ea01d6851065
Create Date: 2024-05-07 00:51:56.250443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b813c5983b99'
down_revision = 'ea01d6851065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parasha', 'humash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parasha', sa.Column('humash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
