"""empty message

Revision ID: d4ee34318992
Revises: 49825a30d02e
Create Date: 2024-03-10 19:46:40.850573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ee34318992'
down_revision = '49825a30d02e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('sessionId', sa.Integer(), nullable=False))
    op.add_column('analysis', sa.Column('rhytem', sa.String(length=255), nullable=True))
    op.add_column('analysis', sa.Column('pitch', sa.String(length=255), nullable=True))
    op.add_column('analysis', sa.Column('wordsAndNoteTiming', sa.String(length=255), nullable=True))
    op.add_column('analysis', sa.Column('vowelsDeviation', sa.String(length=255), nullable=True))
    op.add_column('analysis', sa.Column('wordsMismatch', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'analysis', 'task', ['sessionId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analysis', type_='foreignkey')
    op.drop_column('analysis', 'wordsMismatch')
    op.drop_column('analysis', 'vowelsDeviation')
    op.drop_column('analysis', 'wordsAndNoteTiming')
    op.drop_column('analysis', 'pitch')
    op.drop_column('analysis', 'rhytem')
    op.drop_column('analysis', 'sessionId')
    # ### end Alembic commands ###
