"""empty message

Revision ID: ea01d6851065
Revises: 0bb7289e78e2
Create Date: 2024-05-07 00:35:33.599531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea01d6851065'
down_revision = '0bb7289e78e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('sample_lines', sa.Text(), nullable=True))
    op.add_column('project', sa.Column('sample_syllables', sa.Text(), nullable=True))
    op.alter_column('project', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('project', 'sample_syllables')
    op.drop_column('project', 'sample_lines')
    # ### end Alembic commands ###
